# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cc6254acad7deba16cc3c28c05cf3614a1bd31804d431fafbde841cab800cc079f5fcddfb6642dd36676f46861d1124cae4cac14977db56951b71cf3c9084cb

test:
  secret_key_base: 6d5d578457170f00f0dfe5a0f39fd7ff9178b040a9cac25888ed457e13230df124dcd84bd3142500f83703cae1130885a7f7c18276d87f885895c39db4b000d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
